name: data_readiness
channels:
  - conda-forge
dependencies:
  # Notebooks
  - python=3.10
  - jupyterlab=4.2.*
  - jupyterlab_widgets
  - ipykernel=6.29.*
  - ipywidgets

  # Data Science
  - numpy
  - pandas=2.2.*
  - xarray
  - joblib=1.4.*
  - cartopy
  - seaborn
  - matplotlib

  # Machine Learning
  - scikit-learn=1.5.*
  - keras
  - pytorch=2.4.*
  - tensorflow=2.17.*
  - xgboost=2.1.*

  # File Formats
  - netCDF4=1.6.*
  - cfgrib
  - h5netcdf
  - zarr
  - rasterio

  # Data Access
  - cdsapi
  - beautifulsoup4
  - requests

  # Local Package
  - pip
  - pip: 
    - -e ${DATA_READINESS_PATH}
