name: data_readiness
channels:
  - defaults
  - conda-forge
dependencies:
  # Notebooks 
  - python=3.10
  - jupyterlab=4.2.5
  - ipykernel=6.29.5
  - ipywidgets=8.1.2

  # Data Science
  - numpy=1.26.4
  - pandas=2.2.3
  - xarray=2023.6.0
  - joblib=1.4.2
  - cartopy=0.22.0
  - seaborn=0.13.2
  - matplotlib=3.9.2

  # Machine Learning
  - scikit-learn=1.5.2
  - keras=3.4.1
  - pytorch=2.4.0
  - tensorflow=2.17.0
  - xgboost=2.1.1
  
  # File Formats
  - netCDF4=1.6.2
  - cfgrib=0.9
  - h5netcdf=1.2.0
  - zarr=2.13.3
  - rasterio=1.3.10

  # Data Access
  - cdsapi=0.7.4
  - beautifulsoup4=4.12.3
  - requests=2.32.3
  
  # Local Package
  - pip=24.2
  - pip: 
    - -e ${DATA_READINESS_PATH}
